# Generated by Django 5.0.6 on 2024-07-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('film_description', models.TextField(verbose_name='Описание фильма')),
                ('image', models.ImageField(upload_to='films/img', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Добавить фильм',
                'verbose_name_plural': 'Добавить фильмы',
            },
        ),
        migrations.AlterModelOptions(
            name='film_comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='film_comment',
            name='comment',
            field=models.TextField(verbose_name='Комментарий к фильму'),
        ),
        migrations.AlterField(
            model_name='film_comment',
            name='description',
            field=models.TextField(verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='film_comment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название фильма'),
        ),
    ]
